<<<<<<< HEAD
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
url:
  # Owner/author information
baseurl: /agency-jekyll-theme/

# Site settings
title: Prashant Commmunications
email: prachirpandey03@gmail.com
description: "Planning for Mobile Shopping, recharges, deals? Visit our now to explore mobile phones including mobile prices, recharges plans reviews, comparisons, features, videos, accessories ."


# Team names, titles and social links
people:
- name: Prachir Pandey
  pic: 1
  position: Owner
  social:
    - title: Instagram
      url: https://www.facebook.com/prashantcommunication
    - title: facebook
      url: https://www.facebook.com/prashantcommunication
    - title: Maps
      url: https://goo.gl/maps/KoWVz6WfL9gB69ko9

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: Facebook
    url: https://www.facebook.com/prashantcommunication

# Postal address (add as many lines as necessary)
address:
  - line: Painth Parao, Near Bharat Bar
  - line: Ramnagar, Uttarakhand 244715

# Build settings
markdown: kramdown
permalink: pretty
=======
theme: jekyll-theme-cayman
>>>>>>> dc0aa0426bd8fbc7bd641d8a7ed45e9dc61bc6d0
